name: Auto Approve PR

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write

jobs:
  approve:
    if: |
      github.event.pull_request.user.login == github.repository_owner
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: - name: Auto Approve
  uses: hmarr/auto-approve-action@v4
